# Generated by Django 5.2.5 on 2025-08-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='peice',
            new_name='price',
        ),
    ]
