# Generated by Django 5.2.5 on 2025-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_modeified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
