# Generated by Django 5.2.5 on 2025-09-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_address3',
            new_name='shipping_address2',
        ),
    ]
