# Generated by Django 5.2.5 on 2025-09-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_shippied',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
