# Generated by Django 5.2.5 on 2025-09-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_order_date_shippied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_shippied',
            new_name='date_shipped',
        ),
    ]
